fragment PortfolioParts on Portfolio {
  __typename
  quests {
    __typename
    id
    title
    system
    subtitle
    thumbnail
    challenge
    solution
    images
    stack
    metrics {
      __typename
      label
      value
      desc
    }
  }
}
